### ISSUE TITLE
Need operators for optionals

### ISSUE THREAD

**Issue by dostrander** [Raizlabs/Anchorage#2]
We should to take into consideration the case where one of the layout anchors are optional. If I do this:
`view.leftAnchor == view.window?.leftAnchor` it uses the equality operator rather than anchorage `==` operator.

**Comment by KingOfBrian** [comment]
You get a warning when this happens, correct? 

I'd personally rather force people to unwrap than add a extensions in the optional space.

**Comment by jvisenti** [comment]
I agree with @KingOfBrian, the API should only support unwrapped values. Getting into the optional business would only complicate things.
