### ISSUE TITLE
Use of variables

### ISSUE THREAD

**Issue by vandilsonlima** [Raizlabs/Anchorage#24]
why can't I do this?
`let w = 100`
`view.widthAnchor == w`
Compile says 

> Binary operator '==' cannot be applied to operants of type NSLayoutDimension' and 'Int'

while this is possible
`view.widthAnchor == 100 `

**Comment by ateliercw** [comment]
@vandilsonlima the compiler is inferring that `w` is an int, to use a variable in a layout expression, the value needs to be a `CGFloat`
```
let w: CGFloat = 100
view.widthAnchor == w
```
Should compile

**Comment by vandilsonlima** [comment]
@ateliercw thanks for your help. I didn't notice that I should use a CGFloat instead of an Int.
