### ISSUE TITLE
Shorter anchor properties

### ISSUE THREAD

**Issue by phatmann** [Raizlabs/Anchorage#27]
I love how concise Anchorage makes constraint equations. But we could do even better by providing view properties that drop the `Anchor` suffix and alias the anchor properties. For example:

```
view.top = container.top + 3
view.edges = container.edges
```

If interested, I could put a PR together.

**Comment by jvisenti** [comment]
Thanks for the feedback. However, Anchorage uses the built-in anchor properties, which are currently suffixed with `Anchor`. To provide a shorter version without the suffix, we would have to add our own protocol that exposed the shortened variables and called through to the longer ones. I believe this would cause too much confusion for users not sure of which property to use (even though they would both be the same). Hopefully Apple shortens their properties to drop the suffix in a future Swift version  🙂
