### ISSUE TITLE
Prevent self-constraint

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/Anchorage#31]
I just wrote this by mistake:

```swift
someView.verticalAnchors == someView.verticalAnchors
```

I meant to write the similar but distinct:

```swift
someView.verticalAnchors == someViewContainer.verticalAnchors
```

This could be caught at run-time by asserting that the sides of `==` are not `===`.

**Comment by jvisenti** [comment]
Thanks for the input, but I'm going to leave this out for now. Extra logic required with every constraint created, to check if the LHS and RHS are "equal", and that doesn't seem like a good tradeoff for most cases.
