### ISSUE TITLE
Add convenience syntax for .low + 1

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/Anchorage#34]
With the new enumerations provided in #33, it would be nice to add some extra operators so that you can do:

```swift
view1.leadingAnchor == view2.trailingAnchor ~ .low + 1
```

Instead, you have to do:

```swift
view1.leadingAnchor == view2.trailingAnchor ~ .custom(UILayoutPriorityLow + 1)
```

**Comment by jvisenti** [comment]
@ZevEisenberg In the `Instead...` you can drop the `.custom` because the old API still exists for working with floats directly

**Comment by ZevEisenberg** [comment]
Oops, right. But it's a shame to have to mix and match the old and new APIs.

**Comment by jvisenti** [comment]
Old and new is one way to look at it. Another is two overloads of the same operator like everywhere else in Anchorage 😉
