### ISSUE TITLE
Adjacent operators are in unordered precedence groups 'AdditionPrecedence' and 'PriorityPrecedence'

### ISSUE THREAD

**Issue by ricardopereira** [Raizlabs/Anchorage#47]
I'm using Anchorage version 3.0.0 in a Swift 3 project.
I want to set a priority to a constraint. From the README, I should use the `~` operator.

```
thumbnailTopConstraint = thumbnailImageView.topAnchor == contentView.topAnchor + 15 ~ 950
                                                                                    ^~error
```

**Comment by ricardopereira** [comment]
BTW, this is also yelling `Cannot convert value of type 'Int' to expected argument type 'UILayoutPriority' (aka 'Float')`

so the code should be:
`thumbnailTopConstraint = thumbnailImageView.topAnchor == contentView.topAnchor + 15 ~ UILayoutPriority(950)`

**Comment by ricardopereira** [comment]
Ok, I found a solution 😄: `thumbnailTopConstraint = thumbnailImageView.topAnchor == (contentView.topAnchor + 15) ~ UILayoutPriority(950)`.

**Comment by jvisenti** [comment]
Hey @ricardopereira, the definition for `PriorityPrecedence`, does specify `lowerThan: AdditionPrecedence`. The error I see when trying to compile your example is:
> Cannot convert value of type 'Int' to expected argument type 'Priority'

Your workaround is a fine solution, but the recommended approach for custom priorities is to use an offset from one of the defaults. In your case, that would be `~ .required - 50`.

Alternatives are also `~ 950.0` or `~ .custom(950)`
