### ISSUE TITLE
Manual installation instructions

### ISSUE THREAD

**Issue by chmaynard** [Raizlabs/Anchorage#51]
I plan to use Anchorage in an iOS Swift project soon. I'd prefer to avoid CocoaPods or Carthage and simply add the source files to my project manually. It would be useful to include instructions for a manual installation in the README. Thanks!

**Comment by jvisenti** [comment]
As with any manual source inclusion, simply drag the files into your Xcode project. Not sure this belongs in the README, as the integration steps are exactly the same as any other Swift files.

**Comment by chmaynard** [comment]
Excellent, thanks.
