### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by robcadwallader** [Raizlabs/Anchorage#6]
Anchorage should be made compatible with Swift 3.0. There are a few issues that stand in the way of this goal:
- NSLayoutYAxisAnchor and NSLayoutXAxisAnchor are declared recursively as of Xcode 8 Beta 1. This issue causes the compiler to crash when compiling Anchorage. http://openradar.appspot.com/radar?id=4988511602081792
- The genericized operators passed into ConstraintBuilder's initializer give an "Ambiguous member reference" error. The compiler fails to infer their type from the initializer's parameter types. This is likely related to the aforementioned issue.
- Anchorage's AnchorType protocol name collides with that of a protocol newly added to UIKit.

**Comment by lfarah** [comment]
Hey, any updates on this?

**Comment by KingOfBrian** [comment]
Hey @lfarah -- I missed your question, sorry for not replying. We just published 3.0 so you should be all set for Swift 2.3 or 3.0.

**Comment by lfarah** [comment]
Hey @KingOfBrian, thanks. You're awesome! 👍
