### ISSUE TITLE
Support optional constraints on either side of operators

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/Anchorage#9]
If I'm binding to a view's `superview`, which is a `UIView?`, I need to unwrap it first. It would be nice if `==` had an override for `(lhs: UIView?, rhs: UIView?) -> NSLayoutConstraint?`, so I could write something like:

``` swift
myView.widthAnchor == myView.superView?.widthAnchor
```

**Comment by Alex293** [comment]
+1

**Comment by ZevEisenberg** [comment]
In retrospect, if you're binding to a view's superview, there may be a better way to do what you're trying to do. In general, constraints should look inwards, not outwards. But I'd still like this for dealing with optional views.

**Comment by ZevEisenberg** [comment]
Duplicates #2.
